/* Cepte Not Pro v5 — zero runtime dependencies, backwards-compatible notes. */
(() => {
  'use strict';
  const C = window.CepteCore, $ = id => document.getElementById(id), esc = value => String(value ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const clone = value => JSON.parse(JSON.stringify(value));
  const fmt = value => value ? new Date(value.length===10?value+'T12:00:00':value).toLocaleDateString('tr-TR',{day:'numeric',month:'short'}) : 'Tarihsiz';
  const localTime = value => {if(!value)return '';const d=new Date(value);return C.day(d)+'T'+String(d.getHours()).padStart(2,'0')+':'+String(d.getMinutes()).padStart(2,'0');};
  const options = (values, selected='', all='') => (all?`<option value="">${esc(all)}</option>`:'')+values.map(v=>`<option value="${esc(typeof v==='string'?v:v[0])}" ${selected===(typeof v==='string'?v:v[0])?'selected':''}>${esc(typeof v==='string'?v:v[1])}</option>`).join('');
  let state, storageReady=true, view='today', layout='list', filters={}, query='', selectMode=false, selected=new Set(), limit=100;
  let editorSubs=[], editorFiles=[], detailId=null, toastTimer, undoAction=null, draftTimer, syncing=false, syncTimer, dirty=false;
  let calendarMonth=new Date(new Date().getFullYear(),new Date().getMonth(),1), calendarSelected=C.day(), installEvent=null;
  let alarmId=null, alarmQueue=[], audio=null, alarmTimer=null, recognition=null, dictating=false, dragId=null, lastDay=C.day(), subtaskDrag=null;
  const navItems=[['today','Bugünüm','⌂'],['all','Tüm Görevler','☷'],['waiting','Bekleyenler','◷'],['calendar','Takvim','▦'],['archive','Arşiv','▣'],['trash','Çöp Kutusu','♲'],['categories','Kategoriler','▧'],['statistics','İstatistikler','▥'],['settings','Ayarlar','⚙']];
  try {const oldTheme=localStorage.getItem('theme'),hadV5=!!localStorage.getItem(C.KEY);const loaded=C.load(localStorage);state=loaded.state;if(!hadV5&&['light','dark'].includes(oldTheme))state.settings.theme=oldTheme;dirty=localStorage.getItem('cepte_not_sync_pending')==='true';if(loaded.issues.length){$('storage-warning').hidden=false;$('storage-warning').textContent=loaded.issues.join(' ');}} catch(e){state=C.migrate([]);storageReady=false;$('storage-warning').hidden=false;$('storage-warning').textContent='Tarayıcı kayıt alanına erişilemiyor. Değişiklikleri kaydetmeden önce yedek alın.';}
  function toast(message,undo=null) {if($('download-link'))$('download-link').hidden=true;clearTimeout(toastTimer);$('toast-message').textContent=message;$('toast').hidden=false;undoAction=undo;$('undo-button').hidden=!undo;toastTimer=setTimeout(()=>{$('toast').hidden=true;undoAction=null;},undo?12000:6500);}
  function store(next=state) {
    if(!storageReady){toast('Not kaydedilemedi. Tarayıcının depolama iznini kontrol edin.');return false;}
    try{const old=localStorage.getItem(C.KEY);if(old){try{C.migrate(JSON.parse(old));localStorage.setItem(C.KEY+'_lastgood',old);}catch{localStorage.setItem(C.KEY+'_unreadable',old);}}
      localStorage.setItem(C.KEY,JSON.stringify(next));return true;
    }catch(e){console.error('Yerel kayıt başarısız',e);toast('Not kaydedilemedi. Depolama alanı dolmuş olabilir; JSON yedeği alın.');return false;}
  }
  function commit(message,action,undo=true) {
    const before=clone(state);try{action(state);}catch(e){state=before;console.error('İşlem uygulanamadı',e);toast('İşlem tamamlanamadı.');return false;}
    if(!store()){state=before;return false;}dirty=true;queueSync();render();if(detailId&&$('details').open)renderDetail();
    const after=clone(state);if(message)toast(message,undo?()=>restoreSnapshot(before,after):null);return true;
  }
  function restoreSnapshot(before,after) {
    const current=clone(state),time=new Date().toISOString(),prior=new Map(before.notes.map(n=>[n.id,n])),applied=new Map(after.notes.map(n=>[n.id,n]));
    new Set([...prior.keys(),...applied.keys()]).forEach(id=>{const oldNote=prior.get(id),changed=applied.get(id);if(JSON.stringify(oldNote)===JSON.stringify(changed))return;
      if(oldNote){const restored=clone(oldNote);restored.updatedAt=time;const index=current.notes.findIndex(n=>n.id===id);if(index>=0)current.notes[index]=restored;else current.notes.push(restored);current.tombstones=current.tombstones.filter(t=>t.id!==id);}
      else {current.notes=current.notes.filter(n=>n.id!==id);current.tombstones.push({id,deletedAt:time});}});
    if(JSON.stringify(before.categories)!==JSON.stringify(after.categories)){current.categories=clone(before.categories);current.categoriesUpdatedAt=time;}
    Object.keys(before.settings).forEach(key=>{if(before.settings[key]!==after.settings[key])current.settings[key]=before.settings[key];});
    const old=state;state=current;if(!store()){state=old;return;}dirty=true;queueSync();render();if(detailId&&$('details').open)renderDetail();toast('İşlem geri alındı.');
  }
  const find = id => state.notes.find(n=>n.id===id);
  const stamp = n => {n.updatedAt=new Date().toISOString();};
  function setTheme() {const theme=state.settings.theme;document.documentElement.dataset.theme=theme==='system'?(matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light'):theme;}
  function navigate(next) {view=next;filters={};selected.clear();selectMode=false;query='';$('search').value='';limit=100;if(view==='calendar')layout='calendar';else layout='list';render();window.scrollTo({top:0,behavior:'instant'});}
  function visibleNotes() {
    const shortcut=C.fold(query);const result=state.notes.filter(n=>{
      if(view==='trash')return !!n.deletedAt;
      if(n.deletedAt)return false;
      if(view==='archive')return !!n.archivedAt;
      if(query)return true; // Search also includes archived notes.
      if(n.archivedAt)return false;
      if(view==='waiting')return n.status==='Bekliyor';
      if(view==='completed')return n.completed;
      if(view==='overdue')return C.active(n)&&C.bucket(n)==='overdue';
      if(view==='dueToday')return C.active(n)&&(C.bucket(n)==='today'||n.alarmAt&&C.day(n.alarmAt)===C.day());
      if(view==='upcoming')return C.active(n)&&C.delta(C.due(n))>0&&C.delta(C.due(n))<=7;
      if(view==='today')return C.active(n)&&(C.delta(C.due(n))!==null&&C.delta(C.due(n))<=0||n.alarmAt&&C.day(n.alarmAt)===C.day()||C.delta(C.due(n))>0&&C.delta(C.due(n))<=7&&['Acil','Yüksek'].includes(n.priority));
      if(view==='all'&&layout!=='kanban'&&!filters.status&&!filters.completion)return !n.completed;
      return true;
    });return C.sortNotes(result.filter(n=>C.matches(n,filters,query)), $('sort').value);
  }
  function render() {
    clearSubtaskDrag();setTheme();$('current-date').textContent=new Date().toLocaleDateString('tr-TR',{weekday:'long',day:'numeric',month:'long',year:'numeric'});
    $('desktop-nav').innerHTML=navItems.map(([key,label,icon])=>`<button data-nav="${key}" class="nav-button ${view===key?'active':''}" ${view===key?'aria-current="page"':''}><span class="nav-icon" aria-hidden="true">${icon}</span>${label}${key==='waiting'||key==='trash'?`<span class="nav-count">${state.notes.filter(n=>key==='trash'?n.deletedAt:C.active(n)&&n.status==='Bekliyor').length}</span>`:''}</button>`).join('');
    document.querySelectorAll('.mobile-nav [data-nav]').forEach(b=>{b.classList.toggle('active',b.dataset.nav===view);b.setAttribute('aria-current',b.dataset.nav===view?'page':'false');});
    $('page-title').textContent=({dueToday:'Bugünkü işler',overdue:'Geciken işler',upcoming:'Yaklaşan işler',completed:'Tamamlanan işler'})[view]||navItems.find(n=>n[0]===view)?.[1]||'Görevler';
    const special=['settings','categories','statistics'].includes(view);$('dashboard').hidden=special;$('daily-summary').hidden=special||view!=='today';$('tools').hidden=special;$('bulk-bar').hidden=special||!selectMode;
    renderDashboard();if(view==='today')renderSummary();renderFilters();
    document.querySelectorAll('[data-view]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.view===layout?'true':'false'));
    if(view==='settings'){renderSettings();return;}if(view==='categories'){renderCategories();return;}if(view==='statistics'){renderStatistics();return;}
    const list=visibleNotes();$('result-count').textContent=`${list.length} kayıt`;$('select-mode').textContent=selectMode?'Seçimi kapat':'Seç';renderBulk(list);
    if(layout==='calendar'){renderCalendar(list);return;}if(layout==='kanban'&&!['archive','trash'].includes(view)){renderKanban(list);return;}
    if(!list.length){$('content').innerHTML=empty();return;}
    if(view==='today'&&!query&&!Object.values(filters).some(Boolean))renderToday(list);else $('content').innerHTML=`<div class="task-list">${list.slice(0,limit).map(card).join('')}</div>${more(list.length)}`;
  }
  function renderDashboard(){const live=state.notes.filter(n=>!n.deletedAt&&!n.archivedAt);const active=live.filter(C.active),today=C.day();
    const stats=[['dueToday','Bugün',active.filter(n=>C.bucket(n)==='today'||n.alarmAt&&C.day(n.alarmAt)===today).length,'today'],['overdue','Geciken',active.filter(n=>C.bucket(n)==='overdue').length,'overdue'],['upcoming','Yaklaşan',active.filter(n=>C.delta(C.due(n))>0&&C.delta(C.due(n))<=7).length,''],['waiting','Bekleyen',active.filter(n=>n.status==='Bekliyor').length,'waiting'],['completed','Tamamlanan',live.filter(n=>n.completed).length,'completed']];
    $('dashboard').innerHTML=stats.map(([key,label,count,tone])=>`<button class="stat-card ${tone} ${key===view?'active':''}" data-nav="${key}" aria-label="${label}: ${count} kayıt"><span class="stat-label">${label}</span><strong>${count}</strong></button>`).join('');}
  function renderSummary(){const today=C.day(),done=state.notes.filter(n=>!n.deletedAt&&n.completedAt&&C.day(n.completedAt)===today).length,left=state.notes.filter(n=>C.active(n)&&C.due(n)===today).length,total=done+left,percent=total?Math.round(done/total*100):0;
    $('daily-summary').innerHTML=`<strong>Bugünün özeti</strong><span>${total} iş · ${done} tamamlandı · ${left} kaldı</span><div class="progress" role="progressbar" aria-label="Bugünkü tamamlanma" aria-valuemin="0" aria-valuemax="100" aria-valuenow="${percent}"><i style="width:${percent}%"></i></div><span>%${percent}</span>${left?'<button class="ghost" data-action="move-tomorrow">Kalanları yarına taşı</button>':''}`;}
  function renderFilters(){const names={status:'Durum',category:'Kategori',priority:'Öncelik',date:'Tarih',tag:'Etiket',completion:'Tamamlanma'};
    const values={status:C.STATUSES,category:state.categories.map(c=>c.name),priority:C.PRIORITIES,date:[['today','Bugün'],['tomorrow','Yarın'],['week','Bu hafta'],['future','Gelecek'],['overdue','Gecikmiş'],['undated','Tarihsiz']],tag:[...new Set(state.notes.flatMap(n=>n.tags))].sort((a,b)=>a.localeCompare(b,'tr')),completion:[['open','Tamamlanmamış'],['done','Tamamlanmış']]};
    $('filter-panel').innerHTML=Object.entries(names).map(([key,label])=>`<label>${label}<select data-filter="${key}">${options(values[key],filters[key]||'','Tümü')}</select></label>`).join('');
    $('filter-chips').innerHTML=Object.entries(filters).filter(([,v])=>v).map(([key,v])=>{const label=values[key].find(x=>Array.isArray(x)&&x[0]===v)?.[1]||v;return `<button class="chip" data-action="remove-filter" data-key="${key}" aria-label="${names[key]} filtresini kaldır">${names[key]}: ${esc(label)} ×</button>`;}).join('')+(Object.values(filters).some(Boolean)?'<button class="ghost" data-action="reset-filters">Temizle</button>':'');}
  function empty(compact=false){const first=!state.notes.some(n=>!n.deletedAt);const title=first?'İlk notunuzu ekleyin':query?'Aramanızla eşleşen kayıt yok':view==='today'?'Bugün yapılacak iş kalmadı.':view==='waiting'?'Henüz bekleyen bir işiniz yok.':view==='trash'?'Çöp kutusu boş.':view==='archive'?'Henüz arşivlenen kayıt yok.':'Bu görünümde kayıt yok.';
    return `<div class="empty ${compact?'compact':''}"><div class="empty-symbol" aria-hidden="true">${first?'＋':'✓'}</div><h2>${title}</h2><p>${first?'Not ekle → tarih belirle → takip et.':query?'Başka bir kelime deneyebilir veya filtreleri temizleyebilirsiniz.':'Yeni bir not ekleyebilir ya da tüm görevlerinizi açabilirsiniz.'}</p>${compact?'':`<button class="primary" data-action="add">${first?'İlk Notumu Oluştur':'Hızlı Not'}</button> <button class="ghost" data-nav="all">Tüm Görevler</button>`}</div>`;}
  function relative(n){const d=C.delta(C.due(n));return n.completed?'Tamamlandı':n.status==='İptal'?'İptal':d===null?'Tarihsiz':d<0?`${-d} gün gecikti`:d===0?'Bugün':d===1?'Yarın':`${d} gün kaldı`;}
  function card(n){const id=esc(n.id),progress=n.subTasks.length?Math.round(n.subTasks.filter(s=>s.completed).length/n.subTasks.length*100):0,overdue=C.active(n)&&C.bucket(n)==='overdue',cat=state.categories.find(c=>c.name===n.category),readonly=!!n.deletedAt,pending=n.subTasks.map((s,index)=>({s,index})).filter(({s})=>!s.completed);
    return `<article class="task-card ${overdue?'overdue':''} ${n.completed?'done':''} ${n.pinned?'pinned':''}" data-card-id="${id}" ${layout==='kanban'&&!readonly?'draggable="true"':''}>
      <div class="task-top">${selectMode?`<input type="checkbox" data-select="${id}" aria-label="${esc(n.title)} kaydını seç" ${selected.has(n.id)?'checked':''}>`:`<button class="complete-circle ${n.completed?'done':''}" data-action="complete" data-id="${id}" aria-label="${n.completed?'Yeniden aç':'Tamamla'}: ${esc(n.title)}" ${readonly?'disabled':''}>${n.completed?'✓':''}</button>`}<button class="task-title" data-action="detail" data-id="${id}">${n.pinned?'📌 ':''}${esc(n.title)}</button></div>
      ${n.content?`<p class="task-desc">${esc(n.content)}</p>`:''}<div class="task-meta"><span class="badge" style="color:${cat?.color||'var(--muted)'}">${esc(n.category)}</span><span class="badge ${n.priority==='Acil'?'urgent':n.priority==='Yüksek'?'high':''}">${esc(n.priority)}</span><span class="badge ${n.completed?'done':''}">${esc(n.status)}</span>${n.archivedAt?'<span class="badge">Arşiv</span>':''}${n.repeat!=='none'?'<span class="badge">↻ Tekrar</span>':''}</div>
      ${n.status==='Bekliyor'&&(n.waitingFor||n.waitingSince)?`<p class="waiting-line">${esc(n.waitingFor)}${n.waitingSince?`${n.waitingFor?' · ':''}${Math.max(0,-C.delta(n.waitingSince))} gündür bekliyor`:''}</p>`:''}
      ${n.status==='Bekliyor'&&n.waitingNote?`<p class="waiting-line waiting-note">${esc(n.waitingNote)}</p>`:''}
      ${n.tags.length?`<div>${n.tags.slice(0,4).map(t=>`<button class="tag-btn" data-action="tag" data-tag="${esc(t)}">#${esc(t)}</button>`).join('')}</div>`:''}
      ${n.subTasks.length?`<div class="task-progress"><span>${n.subTasks.filter(s=>s.completed).length} / ${n.subTasks.length} tamamlandı</span><div class="progress"><i style="width:${progress}%"></i></div><span>%${progress}</span></div>`:''}
      ${pending.length?`<section class="card-subtasks" aria-label="Bekleyen alt görevler"><h3>Bekleyen işler <span>${pending.length}</span></h3><ul>${pending.map(({s,index})=>`<li data-subtask-index="${index}"><label><input type="checkbox" data-card-sub="${index}" data-id="${id}" ${readonly?'disabled':''}><span>${esc(s.text)}</span></label>${readonly?'':`<button type="button" class="subtask-drag-handle" data-subtask-drag data-id="${id}" data-index="${index}" aria-label="Sürükleyerek sırayı değiştir: ${esc(s.text)}" aria-keyshortcuts="ArrowUp ArrowDown" title="Basılı tutup yukarı veya aşağı sürükleyin">⠿</button>`}</li>`).join('')}</ul></section>`:''}
      ${n.alarmAt?`<p class="helper">⏰ ${fmt(n.alarmAt)} ${new Date(n.alarmAt).toLocaleTimeString('tr-TR',{hour:'2-digit',minute:'2-digit'})}${n.alarmTriggered?' · Hatırlatıldı':''}</p>`:''}
      <div class="task-bottom"><span class="task-date ${overdue?'overdue':''}">${relative(n)}${C.due(n)?` · ${fmt(C.due(n))}`:''}</span><div class="card-actions">${readonly?`<button data-action="restore" data-id="${id}" title="Geri yükle" aria-label="Geri yükle">↶</button><button data-action="permanent-delete" data-id="${id}" title="Kalıcı sil" aria-label="Kalıcı sil">×</button>`:`<button data-action="snooze" data-id="${id}" aria-label="Tarihi veya hatırlatmayı ertele" title="Ertele">◷</button><button data-action="edit" data-id="${id}" aria-label="Düzenle" title="Düzenle">✎</button><button data-action="menu" data-id="${id}" aria-label="Diğer işlemler" aria-expanded="false">⋯</button>`}</div></div>
      ${layout==='kanban'&&!readonly?`<label class="sr-only" for="status-${id}">Kartı sütuna taşı</label><select id="status-${id}" data-inline="status" data-id="${id}" aria-label="Kartı sütuna taşı">${options(C.STATUSES,n.status)}</select>`:''}
      ${readonly?'':`<div class="card-menu" data-menu="${id}" hidden><button data-action="pin" data-id="${id}">${n.pinned?'Sabitlemeyi kaldır':'📌 Sabitle'}</button><button data-action="copy" data-id="${id}">Kopyala</button><button data-action="archive" data-id="${id}">${n.archivedAt?'Arşivden çıkar':'Arşivle'}</button><button class="danger" data-action="delete" data-id="${id}">Sil</button></div>`}</article>`;}
  const more = total => total>limit?`<button class="secondary load-more" data-action="load-more">Daha fazla göster (${total-limit})</button>`:'';
  function renderToday(list){const groups=[['overdue','Gecikenler',n=>C.bucket(n)==='overdue'],['today','Bugünkü görevler',n=>C.bucket(n)==='today'&&n.status!=='Bekliyor'],['reminders','Bugünkü hatırlatmalar',n=>n.alarmAt&&C.day(n.alarmAt)===C.day()],['waiting','Bugün kontrol edilecekler',n=>n.status==='Bekliyor'&&C.due(n)===C.day()],['important','Yaklaşan önemli işler',n=>C.delta(C.due(n))>0]];
    const shown=new Set();let count=0;$('content').innerHTML=groups.map(([,title,test])=>{const items=list.filter(n=>!shown.has(n.id)&&test(n));items.forEach(n=>shown.add(n.id));if(!items.length)return '';const visible=items.slice(0,Math.max(0,limit-count));count+=visible.length;return `<div class="section-heading"><h2>${title}</h2><small>${items.length}</small></div><div class="task-list">${visible.map(card).join('')}</div>`;}).join('')+more(list.length);}
  function renderKanban(list){const statuses=C.STATUSES.slice(0,4);$('content').innerHTML=`<div class="kanban">${statuses.map(status=>{const items=list.filter(n=>n.status===status);return `<section class="kanban-column" data-drop-status="${esc(status)}"><h3>${status} <small>· ${items.length}</small></h3>${items.slice(0,limit).map(card).join('')}${!items.length?'<p class="helper">Kartı buraya taşıyabilirsiniz.</p>':''}</section>`;}).join('')}</div>${list.some(n=>n.status==='İptal')?`<div class="section-heading"><h2>İptal edilenler</h2></div><div class="task-list">${list.filter(n=>n.status==='İptal').slice(0,limit).map(card).join('')}</div>`:''}${more(list.length)}`;}
  function renderCalendar(list){const first=new Date(calendarMonth),offset=(first.getDay()+6)%7;first.setDate(1-offset);const today=C.day(),days=[];
    for(let i=0;i<42;i++){const d=new Date(first);d.setDate(first.getDate()+i);const s=C.day(d),items=list.filter(n=>C.due(n)===s||n.alarmAt&&C.day(n.alarmAt)===s);days.push(`<button class="calendar-day ${d.getMonth()!==calendarMonth.getMonth()?'other':''} ${s===today?'today':''} ${s===calendarSelected?'selected':''}" data-action="calendar-day" data-date="${s}" ${items.length?`data-count="${items.length} iş"`:''} aria-label="${d.toLocaleDateString('tr-TR')}, ${items.length} kayıt" aria-pressed="${s===calendarSelected}"><span class="day-num">${d.getDate()}</span>${items.slice(0,2).map(n=>`<span class="calendar-event">${esc(n.title)}</span>`).join('')}${items.length>2?`<span class="helper">+${items.length-2}</span>`:''}</button>`);}
    const items=list.filter(n=>C.due(n)===calendarSelected||n.alarmAt&&C.day(n.alarmAt)===calendarSelected);$('content').innerHTML=`<div class="calendar"><div class="calendar-head"><h2>${calendarMonth.toLocaleDateString('tr-TR',{month:'long',year:'numeric'})}</h2><div class="calendar-controls"><button class="icon-btn" data-action="calendar-prev" aria-label="Önceki ay">‹</button><button class="secondary" data-action="calendar-today">Bugün</button><button class="icon-btn" data-action="calendar-next" aria-label="Sonraki ay">›</button></div></div><div class="calendar-grid">${['Pzt','Sal','Çar','Per','Cum','Cmt','Paz'].map(s=>`<div class="calendar-weekday">${s}</div>`).join('')}</div><div class="calendar-grid">${days.join('')}</div></div><div class="calendar-selected"><div class="section-heading"><h2>${fmt(calendarSelected)}</h2><small>${items.length} kayıt</small><button class="ghost" data-action="add-day">＋ Not ekle</button></div>${items.length?`<div class="task-list">${items.slice(0,limit).map(card).join('')}</div>${more(items.length)}`:empty(true)}</div>`;}
  function renderBulk(list){selected=new Set([...selected].filter(id=>list.some(n=>n.id===id)));$('bulk-bar').innerHTML=`<strong>${selected.size} seçildi</strong><button data-action="select-all">Görünen tümünü seç</button>${view==='trash'?'<button data-action="bulk-restore">Geri yükle</button><button class="danger" data-action="empty-trash">Tümünü kalıcı sil</button>':'<button data-action="bulk-complete">Tamamla</button><button data-action="bulk-category">Kategori</button><button data-action="bulk-date">Tarih</button><button data-action="bulk-archive">Arşivle</button><button class="danger" data-action="bulk-delete">Sil</button>'}`;}
  function renderSettings(){$('content').innerHTML=`<div class="settings-grid"><section class="settings-card"><h2>Görünüm ve arşiv</h2><label>Tema<select id="theme-select">${options([['light','Açık'],['dark','Koyu'],['system','Sistem']],state.settings.theme)}</select></label><label class="check-label"><input id="auto-archive" type="checkbox" ${state.settings.autoArchive?'checked':''}>Tamamlandıktan 7 gün sonra arşivle</label></section><section class="settings-card"><h2>Yedekleme ve rapor</h2><p>JSON yedeği tüm kayıtları, alt görevleri, dosyaları, kategorileri ve ayarları içerir.</p><div class="button-row"><button class="primary" data-action="backup">JSON Yedekle</button><button class="secondary" data-action="import">Yedekten Geri Yükle</button><button class="secondary" data-action="csv">CSV / Excel</button><button class="secondary" data-action="txt">TXT Rapor</button><button class="ghost" data-action="legacy-backup">v4 Yedeğini İndir</button></div></section><section class="settings-card"><h2>Hatırlatma ve kurulum</h2><p>Hatırlatmalar sayfa açıkken kontrol edilir. Tarayıcı kapalıyken yeni bildirim gönderilemez; kaçırılan alarmlar açılışta gösterilir.</p><div class="button-row"><button class="secondary" data-action="notifications">Bildirim izni</button><button class="primary" data-action="install">Ana Ekrana Ekle</button></div><p class="helper">${navigator.onLine?'İnternet bağlantısı açık.':'Çevrimdışısınız. Yerel not işlemleri kullanılabilir.'}</p></section><section class="settings-card"><h2>GitHub eşitlemesi</h2><p>Notlarınız önce bu cihazda saklanır, ardından GitHub ile otomatik eşitlenir.</p><div class="button-row"><button class="primary" data-action="sync">Şimdi Eşitle</button></div><p class="helper" id="sync-description">${esc($('sync-status').textContent)}</p><p class="helper">Dosya ekleri bu cihazda ve JSON yedeğinde tutulur; buluta gönderilmez.</p></section></div>`;}
  function renderCategories(){$('content').innerHTML=`<section class="settings-card"><h2>Kategoriler</h2><p>Bir kategoriyi silerseniz kayıtları Diğer kategorisine taşınır.</p><div class="category-editor"><label>Yeni kategori<input id="category-name" placeholder="Kategori adı"></label><label>Renk<select id="category-color">${options(C.COLORS.map((c,i)=>[c,['Mor','Mavi','Pembe','Yeşil','Turuncu','Eflatun','Gri'][i]]))}</select></label><label>Simge<select id="category-icon">${options([['briefcase','💼 İş'],['user','👤 Kişi'],['phone','☎ Telefon'],['calendar','▦ Ajanda'],['tag','▧ Etiket'],['star','★ Önemli']])}</select></label></div><button class="primary" data-action="category-add">Kategori oluştur</button><div>${state.categories.map(c=>`<div class="category-row"><span class="cat-icon" style="color:${c.color}">${categorySymbol(c.icon)}</span><strong>${esc(c.name)}</strong><small>${state.notes.filter(n=>!n.deletedAt&&n.category===c.name).length} kayıt</small><button class="ghost" data-action="category-edit" data-name="${esc(c.name)}">Düzenle</button><button class="ghost danger" data-action="category-delete" data-name="${esc(c.name)}">Sil</button></div>`).join('')}</div></section>`;}
  const categorySymbol = icon => ({briefcase:'💼',user:'👤',phone:'☎',calendar:'▦',tag:'▧',star:'★'})[icon]||'▧';
  function renderStatistics(){const today=C.day(),start=C.plusDay(today,-6),notes=state.notes.filter(n=>!n.deletedAt),created=notes.filter(n=>C.day(n.createdAt)>=start).length,done=notes.filter(n=>n.completedAt&&C.day(n.completedAt)>=start).length,late=notes.filter(n=>C.active(n)&&C.bucket(n)==='overdue').length,counts=Array.from({length:7},(_,i)=>{const d=C.plusDay(start,i);return {day:d,count:notes.filter(n=>n.completedAt&&C.day(n.completedAt)===d).length};}),max=Math.max(1,...counts.map(c=>c.count));
    $('content').innerHTML=`<div class="stats-row"><div class="metric"><span>Son 7 gün oluşturulan</span><strong>${created}</strong></div><div class="metric"><span>Son 7 gün tamamlanan</span><strong>${done}</strong></div><div class="metric"><span>Şu an geciken</span><strong>${late}</strong></div></div><section class="settings-card"><h2>Günlük tamamlanan işler</h2>${counts.map(c=>`<div class="stat-day"><span>${fmt(c.day)}</span><div class="progress"><i style="width:${c.count/max*100}%"></i></div><span>${c.count} tamamlandı</span></div>`).join('')}</section>`;}
  function openEditor(id='',due=null){if($('details').open)$('details').close();detailId=null;const n=id?find(id):null;let draft;
    try{draft=JSON.parse(localStorage.getItem('cepte_not_draft_'+(id||'new'))||'null');}catch{}
    const value=draft||n||C.normalize({id:'new',category:'İş',priority:'Normal',createdAt:new Date().toISOString()});
    $('note-form').reset();$('note-id').value=id;$('editor-title').textContent=id?'Notu düzenle':'Yeni not';$('editor-mode').textContent=id?'GÖREV DETAYLARI':'HIZLI NOT';
    $('note-category').innerHTML=options(state.categories.map(c=>c.name),value.category);$('note-priority').innerHTML=options(C.PRIORITIES,value.priority);$('note-status').innerHTML=options(C.STATUSES,value.status);
    const mapping={title:'title',content:'content',due:'dueDate',start:'startDate',notes:'notes','waiting-for':'waitingFor','waiting-since':'waitingSince',check:'checkDate','waiting-note':'waitingNote',repeat:'repeat','repeat-every':'repeatEvery','repeat-unit':'repeatUnit'};
    Object.entries(mapping).forEach(([field,key])=>$('note-'+field).value=value[key]??'');if(due)$('note-due').value=due;
    $('note-alarm').value=localTime(value.alarmAt);$('note-tags').value=value.tags.join(', ');$('note-links').value=value.links.join(', ');
    editorSubs=clone(value.subTasks);editorFiles=clone(value.attachments);$('advanced-fields').hidden=!id&&!draft;$('expand-button').setAttribute('aria-expanded',!$('advanced-fields').hidden);$('expand-button').textContent=$('advanced-fields').hidden?'Daha Fazla':'Daha Az';
    $('repeat-days').innerHTML=['Paz','Pzt','Sal','Çar','Per','Cum','Cmt'].map((label,d)=>`<label><input type="checkbox" value="${d}" ${value.repeatDays.includes(d)?'checked':''}>${label}</label>`).join('');
    refreshEditorExtras();$('draft-status').textContent=draft?'Kaydedilmemiş taslağınız geri getirildi.':'';renderEditorSubs();renderEditorFiles();$('editor').showModal();$('note-title').focus();}
  function refreshEditorExtras(){$('waiting-fields').hidden=$('note-status').value!=='Bekliyor';if(!$('waiting-fields').hidden&&!$('note-waiting-since').value)$('note-waiting-since').value=C.day();$('repeat-custom').hidden=$('note-repeat').value!=='custom';$('repeat-days').hidden=$('note-repeat').value!=='weekly';}
  function renderEditorSubs(){$('editor-subtasks').innerHTML=editorSubs.map((s,i)=>`<div class="subtask-row"><label><input type="checkbox" data-editor-sub="${i}" ${s.completed?'checked':''}><span>${esc(s.text)}</span></label><button type="button" data-action="remove-subtask" data-index="${i}" aria-label="Alt görevi sil">×</button></div>`).join('');}
  function renderEditorFiles(){$('editor-files').innerHTML=editorFiles.map((f,i)=>`<div class="file-row"><span>${esc(f.name)}</span><button type="button" data-action="remove-file" data-index="${i}" aria-label="Dosyayı kaldır">×</button></div>`).join('');}
  function readEditor(){const id=$('note-id').value,old=find(id),iso=new Date().toISOString(),status=$('note-status').value;
    return C.normalize({...old,id:id||C.uid(),title:$('note-title').value.trim(),content:$('note-content').value,category:$('note-category').value,priority:$('note-priority').value,status,completed:status==='Tamamlandı',dueDate:$('note-due').value||null,startDate:$('note-start').value||null,
      alarmAt:$('note-alarm').value?new Date($('note-alarm').value).toISOString():null,alarmTriggered:old?.alarmAt&&localTime(old.alarmAt)===$('note-alarm').value?old.alarmTriggered:false,
      tags:$('note-tags').value.split(/[,;]+/).map(t=>t.trim().replace(/^#/,'')).filter(Boolean),waitingFor:$('note-waiting-for').value,waitingSince:$('note-waiting-since').value||null,checkDate:$('note-check').value||null,waitingNote:$('note-waiting-note').value,notes:$('note-notes').value,
      links:$('note-links').value.split(/[,\n]+/).map(s=>s.trim()).filter(Boolean),attachments:clone(editorFiles),subTasks:clone(editorSubs),repeat:$('note-repeat').value,repeatEvery:+$('note-repeat-every').value,repeatUnit:$('note-repeat-unit').value,repeatDays:[...$('repeat-days').querySelectorAll('input:checked')].map(i=>+i.value),createdAt:old?.createdAt||iso,updatedAt:iso,completedAt:status==='Tamamlandı'?old?.completedAt||iso:null});}
  function saveDraft(){clearTimeout(draftTimer);if(!$('editor').open)return;try{const data=readEditor();if(!data.title&&!data.content&&!data.subTasks.length&&!data.attachments.length)return;localStorage.setItem('cepte_not_draft_'+($('note-id').value||'new'),JSON.stringify(data));$('draft-status').textContent='Taslak bu cihazda saklandı.';}catch(e){$('draft-status').textContent='Taslak saklanamadı. Kaydet düğmesini kullanın.';}}
  function closeEditor(){saveDraft();if(recognition)recognition.stop();$('editor').close();}
  async function saveEditor(){if(!$('note-form').reportValidity())return;const n=readEditor();if(!n.title){$('note-title').focus();return;}if(n.startDate&&n.dueDate&&n.startDate>n.dueDate){toast('Son tarih başlangıç tarihinden önce olamaz.');return;}if(n.links.some(l=>!safeUrl(l))){toast('Bağlantılar http:// veya https:// ile başlamalı.');return;}
    const id=$('note-id').value;const ok=commit(id?'Not güncellendi.':'Not kaydedildi.',s=>{const index=s.notes.findIndex(x=>x.id===n.id),old=index>=0?s.notes[index]:null;if(index>=0)s.notes[index]=n;else s.notes.unshift(n);
      if(n.completed&&(!old||!old.completed)){n.status='Yapılacak';n.completed=false;C.complete(s,n.id);}} ,false);
    if(ok){clearTimeout(draftTimer);localStorage.removeItem('cepte_not_draft_'+(id||'new'));$('editor').close();}}
  function safeUrl(url){try{const parsed=new URL(url);return ['https:','http:'].includes(parsed.protocol)?parsed.href:null;}catch{return null;}}
  function openDetail(id){const n=find(id);if(!n)return;detailId=id;renderDetail();$('details').showModal();}
  function renderDetail(){const n=find(detailId);if(!n){$('details').close();detailId=null;return;}const id=esc(n.id);
    $('detail-content').innerHTML=`<div class="dialog-head"><h2>${esc(n.title)}</h2><button class="icon-btn" data-action="close-detail" aria-label="Detayı kapat">×</button></div><div class="dialog-body"><span class="badge">${esc(n.category)}</span> <span class="badge ${C.bucket(n)==='overdue'?'overdue':''}">${relative(n)}</span><p class="detail-description">${esc(n.content||'Açıklama eklenmemiş.')}</p>${n.deletedAt?`<p class="helper">${fmt(n.deletedAt)} tarihinde çöp kutusuna taşındı.</p>`:`<div class="detail-grid"><label>Durum<select data-inline="status" data-id="${id}">${options(C.STATUSES,n.status)}</select></label><label>Öncelik<select data-inline="priority" data-id="${id}">${options(C.PRIORITIES,n.priority)}</select></label><label>Kategori<select data-inline="category" data-id="${id}">${options(state.categories.map(c=>c.name),n.category)}</select></label><label>Son tarih<input data-inline="dueDate" data-id="${id}" type="date" value="${n.dueDate||''}"></label><label>Hatırlatma<input data-inline="alarmAt" data-id="${id}" type="datetime-local" value="${localTime(n.alarmAt)}"></label><label>Etiketler<input data-inline="tags" data-id="${id}" value="${esc(n.tags.join(', '))}"></label></div>`}
      ${n.status==='Bekliyor'?`<div class="detail-section"><h3>Bekleme bilgileri</h3><label>Kimden bekleniyor?<input data-inline="waitingFor" data-id="${id}" value="${esc(n.waitingFor)}" ${n.deletedAt?'disabled':''}></label><label>Kontrol tarihi<input data-inline="checkDate" data-id="${id}" type="date" value="${n.checkDate||''}" ${n.deletedAt?'disabled':''}></label><p class="helper">${esc(n.waitingNote)}</p></div>`:''}
      <div class="detail-section"><h3>Alt görevler</h3>${n.subTasks.map((s,i)=>`<div class="subtask-row"><label><input type="checkbox" data-detail-sub="${i}" ${s.completed?'checked':''} ${n.deletedAt?'disabled':''}><span>${esc(s.text)}</span></label></div>`).join('')}${n.deletedAt?'':`<div class="inline-form"><input id="detail-new-sub" aria-label="Yeni alt görev" placeholder="Alt görev ekle"><button class="secondary" data-action="detail-add-sub">Ekle</button></div>`}</div>
      ${n.notes?`<div class="detail-section"><h3>Ek notlar</h3><p class="detail-description">${esc(n.notes)}</p></div>`:''}${n.links.length?`<div class="detail-section"><h3>Bağlantılar</h3>${n.links.map(l=>safeUrl(l)?`<p><a href="${esc(safeUrl(l))}" target="_blank" rel="noopener noreferrer">${esc(l)}</a></p>`:`<p>${esc(l)}</p>`).join('')}</div>`:''}${n.attachments.length?`<div class="detail-section"><h3>Dosyalar</h3>${n.attachments.map((f,i)=>`<button class="secondary" data-action="download-file" data-id="${id}" data-index="${i}">${esc(f.name)}</button>`).join('')}</div>`:''}
      <p class="helper detail-section">Oluşturma: ${fmt(n.createdAt)} · Güncelleme: ${fmt(n.updatedAt)}</p></div><div class="dialog-foot">${n.deletedAt?`<button class="primary" data-action="restore" data-id="${id}">Geri Yükle</button>`:`<button class="secondary" data-action="edit" data-id="${id}">Düzenle</button><button class="primary" data-action="complete" data-id="${id}">${n.completed?'Yeniden Aç':'Tamamla'}</button>`}</div>`;}
  function updateInline(id,field,value){const n=find(id);if(!n||n.deletedAt)return;if(field==='status'&&value==='Tamamlandı'&&!n.completed){complete(id);return;}
    commit('Değişiklik kaydedildi.',()=>{const x=find(id);x[field]=field==='tags'?value.split(/[,;]+/).map(t=>t.trim().replace(/^#/, '')).filter(Boolean):field==='alarmAt'?value?new Date(value).toISOString():null:field.endsWith('Date')?value||null:value;
      if(field==='status'){x.completed=value==='Tamamlandı';x.completedAt=x.completed?new Date().toISOString():null;if(value==='Bekliyor'&&!x.waitingSince)x.waitingSince=C.day();}if(field==='alarmAt')x.alarmTriggered=false;stamp(x);});}
  function complete(id){const n=find(id);if(!n||n.deletedAt)return;commit(n.completed?'Görev yeniden açıldı.':'Görev tamamlandı.',s=>C.complete(s,id));}
  function updateSubtask(id,index,checked){const n=find(id);if(!n||n.deletedAt||!n.subTasks[index])return;
    commit('Alt görev güncellendi.',()=>{n.subTasks[index].completed=checked;if(n.subTasks.length&&n.subTasks.every(s=>s.completed)&&!n.completed)C.complete(state,n.id);else if(n.completed){n.completed=false;n.status='Yapılacak';n.completedAt=null;}stamp(n);});}
  function moveSubtask(id,index,direction){const n=find(id);if(!n||n.deletedAt||![1,-1].includes(direction))return;
    const pending=n.subTasks.map((s,i)=>s.completed?-1:i).filter(i=>i>=0),position=pending.indexOf(index),other=pending[position+direction];if(position<0||other===undefined)return;
    commit('İş sırası güncellendi.',()=>{[n.subTasks[index],n.subTasks[other]]=[n.subTasks[other],n.subTasks[index]];stamp(n);});}
  function reorderSubtasks(id,order){const n=find(id);if(!n||n.deletedAt)return false;const pending=n.subTasks.map((s,i)=>s.completed?-1:i).filter(i=>i>=0);
    if(order.length!==pending.length||new Set(order).size!==pending.length||order.some(i=>!pending.includes(i))||order.every((i,p)=>i===pending[p]))return false;
    const moved=order.map(i=>n.subTasks[i]);return commit('İş sırası güncellendi.',()=>{pending.forEach((index,p)=>n.subTasks[index]=moved[p]);stamp(n);});}
  function clearSubtaskDrag(){const drag=subtaskDrag;if(!drag)return null;subtaskDrag=null;cancelAnimationFrame(drag.frame);drag.ghost?.remove();drag.row.classList.remove('subtask-dragging');document.body.classList.remove('subtask-reordering');if(drag.handle.hasPointerCapture(drag.pointerId))drag.handle.releasePointerCapture(drag.pointerId);return drag;}
  function endSubtaskDrag(save){const drag=clearSubtaskDrag();if(!drag?.active)return;const order=[...drag.list.children].map(row=>+row.dataset.subtaskIndex);
    if(!save||!drag.list.isConnected||!reorderSubtasks(drag.id,order))render();}
  function positionSubtaskDrag(){const drag=subtaskDrag;if(!drag?.active)return;if(!drag.list.isConnected){clearSubtaskDrag();return;}
    const edge=64,speed=drag.y<edge?-Math.ceil((edge-drag.y)/4):drag.y>window.innerHeight-edge?Math.ceil((drag.y-window.innerHeight+edge)/4):0;if(speed)window.scrollBy(0,Math.max(-20,Math.min(20,speed)));
    drag.ghost.style.top=(drag.y-drag.offset)+'px';const other=[...drag.list.children].filter(row=>row!==drag.row),anchor=other.find(row=>{const rect=row.getBoundingClientRect();return drag.y<rect.top+rect.height/2;});
    if(drag.row.nextElementSibling!==(anchor||null))drag.list.insertBefore(drag.row,anchor||null);drag.frame=requestAnimationFrame(positionSubtaskDrag);}
  async function ask(title,body,buttons=[['ok','Onayla','primary'],['cancel','İptal','secondary']]){if($('confirmation').open)$('confirmation').close();$('confirm-title').textContent=title;$('confirm-body').innerHTML=body;$('confirm-buttons').innerHTML=buttons.map(([value,label,cls])=>`<button value="${value}" class="${cls}" type="submit">${label}</button>`).join('');$('confirmation').returnValue='cancel';$('confirmation').showModal();return new Promise(resolve=>$('confirmation').addEventListener('close',()=>resolve($('confirmation').returnValue),{once:true}));}
  async function deleteNotes(ids){if(await ask('Çöp kutusuna taşı',`<p>${ids.length} kayıt çöp kutusuna taşınacak. 30 gün içinde geri yükleyebilirsiniz.</p>`,[['ok','Sil','primary'],['cancel','Vazgeç','secondary']])!=='ok')return;commit('Kayıt çöp kutusuna taşındı.',()=>ids.forEach(id=>{const n=find(id);if(n){n.deletedAt=new Date().toISOString();stamp(n);}}));if($('details').open){$('details').close();detailId=null;}}
  async function permanentDelete(ids){if(await ask('Kalıcı silme',`<p>${ids.length} kayıt kalıcı olarak silinsin mi? Bu işlem geri alınamaz.</p>`,[['ok','Kalıcı Sil','primary'],['cancel','Vazgeç','secondary']])!=='ok')return;commit('Kayıtlar kalıcı olarak silindi.',s=>{ids.forEach(id=>s.tombstones.push({id,deletedAt:new Date().toISOString()}));s.notes=s.notes.filter(n=>!ids.includes(n.id));},false);if($('details').open){$('details').close();detailId=null;}}
  async function snooze(id){const n=find(id);if(!n)return;const result=await ask('Ertele',`<p>${esc(n.title)}</p>`,[['10','10 dk','secondary'],['60','1 saat','secondary'],['tomorrow','Yarın 09:00','primary'],['cancel','İptal','ghost']]);if(result==='cancel')return;snoozeApply(id,result);}
  function snoozeApply(id,minutes){const when=new Date();if(minutes==='tomorrow'){when.setDate(when.getDate()+1);when.setHours(9,0,0,0);}else when.setMinutes(when.getMinutes()+Number(minutes));commit('Hatırlatma ertelendi.',()=>{const n=find(id);n.alarmAt=when.toISOString();n.alarmTriggered=false;if(minutes==='tomorrow'){if(n.status==='Bekliyor')n.checkDate=C.day(when);else n.dueDate=C.day(when);}stamp(n);});}
  function download(content,name,type='application/json'){const blob=new Blob([content],{type:type+';charset=utf-8'}),url=URL.createObjectURL(blob);let link=$('download-link');if(!link){link=document.createElement('a');link.id='download-link';link.className='download-link';$('toast').appendChild(link);}link.href=url;link.download=name;link.textContent='Dosyayı indir';toast('Dosya hazır.');link.hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>{$('toast').hidden=true;link.hidden=true;URL.revokeObjectURL(url);},60000);}
  function backup(){download(JSON.stringify({...state,exportedAt:new Date().toISOString()},null,2),`cepte-not-yedek-${C.day()}.json`);}
  async function importBackup(file){if(!file)return;let incoming;try{incoming=C.migrate(JSON.parse(await file.text()));}catch(e){toast('Yedek okunamadı. Geçerli bir Cepte Not JSON dosyası seçin.');return;}
    const result=await ask('Yedeği geri yükle',`<p>${incoming.notes.length} kayıt bulundu. Mevcut kayıtlarla birleştirebilir veya veriyi değiştirebilirsiniz. İşlem öncesi bu cihazda güvenli yedek tutulur.</p>`,[['merge','Birleştir','primary'],['replace','Mevcut veriyi değiştir','secondary'],['cancel','İptal','ghost']]);if(result==='cancel')return;
    const before=clone(state);try{localStorage.setItem('cepte_not_before_import',JSON.stringify(before));}catch{toast('İçe aktarma öncesi yedek oluşturulamadı.');return;}
    // A restore is an explicit edit: date it now so older cloud snapshots cannot overwrite it.
    const now=new Date().toISOString();incoming.notes.forEach(n=>n.updatedAt=now);
    if(result==='replace'){const incomingIds=new Set(incoming.notes.map(n=>n.id));before.notes.filter(n=>!incomingIds.has(n.id)).forEach(n=>incoming.tombstones.push({id:n.id,deletedAt:now}));state=incoming;}else{incoming.notes.forEach(n=>{state.tombstones=state.tombstones.filter(t=>t.id!==n.id);});state=C.merge(state,incoming);}
    if(!store()){state=before;return;}dirty=true;queueSync();render();const after=clone(state);toast('Yedek geri yüklendi.',()=>restoreSnapshot(before,after));}
  async function addFiles(files){const additions=[];for(const file of files){if(file.size>2*1024*1024){toast(`${file.name}: dosya 2 MB sınırını aşıyor.`);continue;}const data=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(file);});additions.push({name:file.name,type:file.type,size:file.size,data});}editorFiles.push(...additions);renderEditorFiles();saveDraft();}
  function sound(){try{audio=audio||new (window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume();const osc=audio.createOscillator(),gain=audio.createGain();osc.frequency.value=880;gain.gain.setValueAtTime(.12,audio.currentTime);gain.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.4);osc.connect(gain);gain.connect(audio.destination);osc.start();osc.stop(audio.currentTime+.45);}catch{}}
  function dismissAlarm(){clearInterval(alarmTimer);$('alarm-dialog').close();alarmId=null;setTimeout(showNextAlarm,50);}
  function showNextAlarm(){if(alarmId||!alarmQueue.length||document.querySelector('dialog[open]'))return;const id=alarmQueue.shift(),n=find(id);if(!n||!C.active(n))return showNextAlarm();alarmId=id;$('alarm-title').textContent=n.title;$('alarm-dialog').showModal();sound();alarmTimer=setInterval(sound,2000);
    if('Notification' in window&&Notification.permission==='granted'){navigator.serviceWorker?.ready.then(reg=>reg.showNotification('Cepte Not Hatırlatıcısı',{body:n.title,tag:n.id,icon:'./icons/icon-192.png',data:{id:n.id}})).catch(()=>{try{new Notification('Cepte Not Hatırlatıcısı',{body:n.title,tag:n.id});}catch{}});}}
  function tick(){const now=Date.now(),due=state.notes.filter(n=>C.active(n)&&n.alarmAt&&!n.alarmTriggered&&Date.parse(n.alarmAt)<=now);if(due.length){const before=clone(state);due.forEach(n=>{n.alarmTriggered=true;stamp(n);});if(store()){dirty=true;queueSync();alarmQueue.push(...due.map(n=>n.id));render();}else state=before;}showNextAlarm();if(C.day()!==lastDay){lastDay=C.day(), subtaskDrag=null;if(C.housekeeping(state))store();render();}}
  async function notifications(){if(!('Notification' in window)){toast('Bu tarayıcı bildirimleri desteklemiyor. Uygulama içi alarmlar çalışır.');return;}if(Notification.permission==='denied'){toast('Bildirimler kapalı. Tarayıcının site izinlerinden bildirimleri açabilirsiniz.');return;}const permission=await Notification.requestPermission();toast(permission==='granted'?'Bildirimler açıldı.':'Bildirim izni verilmedi. Uygulama içi alarmlar çalışır.');}
  function voice(){const Speech=window.SpeechRecognition||window.webkitSpeechRecognition;if(!Speech){toast('Sesli yazma bu tarayıcıda desteklenmiyor. Metni klavyeyle yazabilirsiniz.');return;}if(dictating){recognition.stop();return;}recognition=new Speech();recognition.lang='tr-TR';recognition.interimResults=false;recognition.onstart=()=>{dictating=true;$('voice-button').textContent='Dinliyorum…';$('voice-button').classList.add('listening');};recognition.onend=()=>{dictating=false;$('voice-button').textContent='Sesli Yaz';$('voice-button').classList.remove('listening');};recognition.onerror=e=>toast(e.error==='not-allowed'?'Mikrofon izni verilmedi.':'Ses algılanamadı. Tekrar deneyebilirsiniz.');recognition.onresult=e=>{const text=e.results[0][0].transcript;$('note-content').value+=($('note-content').value?' ':'')+text;
      const folded=C.fold(text),m=folded.match(/saat\s*(\d{1,2})(?:[.:](\d{2}))?/);if(m&&+m[1]<24&&+(m[2]||0)<60){const d=new Date();if(folded.includes('yarin'))d.setDate(d.getDate()+1);d.setHours(+m[1],+(m[2]||0),0,0);$('note-alarm').value=localTime(d);$('note-due').value=C.day(d);$('advanced-fields').hidden=false;}saveDraft();};try{recognition.start();}catch{toast('Mikrofon başlatılamadı.');}}
  const apiUrl=()=>`https://api.github.com/repos/${window.CEPTE_CLOUD.owner}/${window.CEPTE_CLOUD.repo}/contents/${window.CEPTE_CLOUD.path}`;
  const authHeaders=()=>({'Authorization':'token '+window.CEPTE_CLOUD.token,'Accept':'application/vnd.github+json','Content-Type':'application/json'});
  function decodeCloud(content){const bytes=Uint8Array.from(atob(content.replace(/\s/g,'')),c=>c.charCodeAt(0));return JSON.parse(new TextDecoder().decode(bytes));}
  function encodeCloud(value){const bytes=new TextEncoder().encode(JSON.stringify(value,null,2));let s='';for(let i=0;i<bytes.length;i+=8192)s+=String.fromCharCode(...bytes.subarray(i,i+8192));return btoa(s);}
  function syncStatus(text,error=false){$('sync-status').textContent=text;$('sync-status').classList.toggle('error',error);if($('sync-description'))$('sync-description').textContent=text;}
  function queueSync(){try{localStorage.setItem('cepte_not_sync_pending','true');}catch{}clearTimeout(syncTimer);syncTimer=setTimeout(()=>syncCloud(true),1600);}
  function mergeCloud(remote){const merged=C.merge(state,remote);merged.notes.forEach(n=>{const local=find(n.id);if(local?.attachments?.length)n.attachments=local.attachments;});return merged;}
  async function syncCloud(write=false){if(syncing)return;if(!navigator.onLine){syncStatus('Çevrimdışı · cihazda kayıtlı');return;}syncing=true;syncStatus('Eşitleniyor…');
    try{for(let attempt=0;attempt<3;attempt++){const response=await fetch(apiUrl(),{headers:authHeaders(),cache:'no-store',signal:AbortSignal.timeout(15000)});if(!response.ok)throw new Error('GitHub '+response.status);const data=await response.json(),remote=decodeCloud(data.content);if(Array.isArray(remote)&&!localStorage.getItem('cepte_not_v4_backup'))localStorage.setItem('cepte_not_v4_backup',JSON.stringify(remote));const merged=mergeCloud(remote),old=state;state=merged;if(!store()){state=old;throw new Error('Yerel kayıt');}render();
        if(write||dirty){const payload=clone(state);payload.notes.forEach(n=>n.attachments=[]);const snapshot=JSON.stringify(state);const put=await fetch(apiUrl(),{method:'PUT',headers:authHeaders(),signal:AbortSignal.timeout(20000),body:JSON.stringify({message:'Update via Cepte Not v5',content:encodeCloud(payload),sha:data.sha})});if(put.status===409||put.status===422){continue;}if(!put.ok)throw new Error('GitHub '+put.status);dirty=JSON.stringify(state)!==snapshot;try{localStorage.setItem('cepte_not_sync_pending',String(dirty));}catch{}if(dirty)queueSync();}
        syncStatus('Güncel · Bulut');return;}
      throw new Error('Eşitleme çakışması');
    }catch(e){console.error('Bulut eşitlemesi başarısız',e.message);syncStatus('Cihazda kayıtlı · buluta erişilemiyor',true);}
    finally{syncing=false;}}
  async function categoryEdit(name){const cat=state.categories.find(c=>c.name===name);if(!cat)return;const answer=await ask('Kategoriyi düzenle',`<label>Ad<input id="edit-cat-name" value="${esc(cat.name)}"></label><label>Renk<select id="edit-cat-color">${options(C.COLORS.map((c,i)=>[c,['Mor','Mavi','Pembe','Yeşil','Turuncu','Eflatun','Gri'][i]]),cat.color)}</select></label><label>Simge<select id="edit-cat-icon">${options([['briefcase','💼 İş'],['user','👤 Kişi'],['phone','☎ Telefon'],['calendar','▦ Ajanda'],['tag','▧ Etiket'],['star','★ Önemli']],cat.icon)}</select></label>`,[['ok','Kaydet','primary'],['cancel','İptal','secondary']]);if(answer!=='ok')return;const newName=$('edit-cat-name').value.trim(),color=$('edit-cat-color').value,icon=$('edit-cat-icon').value;if(!newName||state.categories.some(c=>c.name===newName&&c.name!==name)){toast('Farklı bir kategori adı yazın.');return;}commit('Kategori güncellendi.',()=>{Object.assign(state.categories.find(c=>c.name===name),{name:newName,color,icon});state.categoriesUpdatedAt=new Date().toISOString();state.notes.filter(n=>n.category===name).forEach(n=>{n.category=newName;stamp(n);});});}
  async function bulkField(field){if(!selected.size){toast('Önce kayıt seçin.');return;}const answer=await ask(field==='category'?'Kategori değiştir':'Tarih değiştir',field==='category'?`<label>Kategori<select id="bulk-value">${options(state.categories.map(c=>c.name))}</select></label>`:'<label>Tarih<input id="bulk-value" type="date"></label>');if(answer!=='ok')return;const value=$('bulk-value').value;commit('Seçilen kayıtlar güncellendi.',()=>selected.forEach(id=>{const n=find(id);if(n){n[field]=value||null;stamp(n);}}));}
  document.addEventListener('click',async event=>{const b=event.target.closest('[data-action],[data-nav],[data-view]');if(!b)return;if(b.dataset.nav){event.preventDefault();navigate(b.dataset.nav);return;}if(b.dataset.view){layout=b.dataset.view;limit=100;if(view==='today'&&layout!=='list'){view='all';}render();return;}const action=b.dataset.action,id=b.dataset.id,n=find(id);
    switch(action){
      case 'add':openEditor();break;case 'edit':openEditor(id);break;case 'add-day':openEditor('',calendarSelected);break;case 'detail':openDetail(id);break;
      case 'close-editor':closeEditor();break;case 'close-detail':$('details').close();detailId=null;break;case 'expand':$('advanced-fields').hidden=!$('advanced-fields').hidden;b.textContent=$('advanced-fields').hidden?'Daha Fazla':'Daha Az';b.setAttribute('aria-expanded',!$('advanced-fields').hidden);break;
      case 'discard-draft':if(await ask('Taslağı sil','<p>Kaydedilmemiş değişiklikler silinsin mi?</p>')==='ok'){clearTimeout(draftTimer);localStorage.removeItem('cepte_not_draft_'+($('note-id').value||'new'));$('editor').close();}break;
      case 'add-subtask':{const text=$('subtask-input').value.trim();if(text){editorSubs.push({id:C.uid(),text,completed:false});$('subtask-input').value='';renderEditorSubs();saveDraft();$('subtask-input').focus();}break;}
      case 'remove-subtask':editorSubs.splice(+b.dataset.index,1);renderEditorSubs();saveDraft();break;case 'remove-file':editorFiles.splice(+b.dataset.index,1);renderEditorFiles();saveDraft();break;
      case 'detail-add-sub':{const text=$('detail-new-sub').value.trim();if(text)commit('Alt görev eklendi.',()=>{const n=find(detailId);n.subTasks.push({id:C.uid(),text,completed:false});stamp(n);});break;}
      case 'complete':complete(id);break;case 'delete':deleteNotes([id]);break;case 'permanent-delete':permanentDelete([id]);break;case 'restore':commit('Kayıt geri yüklendi.',()=>{n.deletedAt=null;stamp(n);});break;
      case 'pin':commit(n.pinned?'Sabitleme kaldırıldı.':'Not sabitlendi.',()=>{n.pinned=!n.pinned;stamp(n);});break;
      case 'archive':commit(n.archivedAt?'Arşivden çıkarıldı.':'Not arşivlendi.',()=>{n.archivedAt=n.archivedAt?null:new Date().toISOString();stamp(n);});break;
      case 'copy':commit('Not kopyalandı.',s=>{s.notes.unshift(C.normalize({...clone(n),id:C.uid(),title:n.title+' (Kopya)',completed:false,status:'Yapılacak',completedAt:null,archivedAt:null,deletedAt:null,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),nextOccurrenceId:null,recurrenceParent:null,alarmTriggered:false}));});break;
      case 'menu':{const menu=b.closest('.task-card').querySelector('[data-menu]'),opening=menu.hidden;document.querySelectorAll('[data-menu]').forEach(m=>m.hidden=true);menu.hidden=!opening;b.setAttribute('aria-expanded',opening);break;}
      case 'snooze':snooze(id);break;case 'tag':filters.tag=b.dataset.tag;view='all';render();break;
      case 'filters':$('filter-panel').hidden=!$('filter-panel').hidden;b.setAttribute('aria-expanded',!$('filter-panel').hidden);break;case 'remove-filter':delete filters[b.dataset.key];render();break;case 'reset-filters':filters={};query='';$('search').value='';render();break;
      case 'select-mode':selectMode=!selectMode;selected.clear();render();break;case 'select-all':visibleNotes().forEach(n=>selected.add(n.id));render();break;
      case 'bulk-complete':commit('Seçilen görevler tamamlandı.',s=>[...selected].forEach(id=>{if(!find(id).completed)C.complete(s,id);}));break;
      case 'bulk-category':bulkField('category');break;case 'bulk-date':bulkField('dueDate');break;case 'bulk-archive':commit('Seçilen kayıtlar arşivlendi.',()=>selected.forEach(id=>{const n=find(id);n.archivedAt=new Date().toISOString();stamp(n);}));break;
      case 'bulk-delete':if(selected.size)deleteNotes([...selected]);else toast('Önce kayıt seçin.');break;case 'bulk-restore':commit('Kayıtlar geri yüklendi.',()=>selected.forEach(id=>{const n=find(id);n.deletedAt=null;stamp(n);}));break;
      case 'empty-trash':permanentDelete(state.notes.filter(n=>n.deletedAt).map(n=>n.id));break;
      case 'move-tomorrow':{const ids=state.notes.filter(n=>C.active(n)&&C.due(n)===C.day()).map(n=>n.id);if(await ask('Kalan işleri yarına taşı',`<p>Bugüne ait ${ids.length} iş yarına taşınacak.</p>`)==='ok')commit('Kalan işler yarına taşındı.',()=>ids.forEach(id=>{const n=find(id);if(n.status==='Bekliyor'&&n.checkDate)n.checkDate=C.plusDay(C.day(),1);else n.dueDate=C.plusDay(C.day(),1);stamp(n);}));break;}
      case 'calendar-day':calendarSelected=b.dataset.date;render();break;case 'calendar-prev':calendarMonth.setMonth(calendarMonth.getMonth()-1);render();break;case 'calendar-next':calendarMonth.setMonth(calendarMonth.getMonth()+1);render();break;case 'calendar-today':calendarMonth=new Date(new Date().getFullYear(),new Date().getMonth(),1);calendarSelected=C.day();render();break;
      case 'theme':commit('',()=>{const themes=['light','dark','system'];state.settings.theme=themes[(themes.indexOf(state.settings.theme)+1)%3];},false);break;
      case 'backup':backup();break;case 'csv':download(C.csv(state.notes.filter(n=>!n.deletedAt)),`cepte-not-${C.day()}.csv`,'text/csv');break;
      case 'txt':download('CEPTE NOT PRO — AJANDA RAPORU\n'+new Date().toLocaleString('tr-TR')+'\n\n'+state.notes.filter(n=>!n.deletedAt).map(n=>`${n.completed?'[✓]':'[ ]'} ${n.title}\n${n.category} · ${n.priority} · ${n.status} · ${fmt(n.dueDate)}\n${n.content}\n${n.subTasks.map(s=>`  [${s.completed?'X':' '}] ${s.text}`).join('\n')}\n`).join('\n'),`cepte-not-toplu-rapor-${C.day()}.txt`,'text/plain');break;
      case 'import':$('import-file').value='';$('import-file').click();break;case 'legacy-backup':{const old=localStorage.getItem('cepte_not_v4_backup')||localStorage.getItem(C.LEGACY);if(old)download(old,'cepte-not-v4-yedek.json');else toast('Bu cihazda v4 yedeği bulunmuyor.');break;}
      case 'download-file':{const f=n.attachments[+b.dataset.index];if(f&&/^data:[^,]*;base64,/.test(f.data||'')){const binary=atob(f.data.split(',')[1]);download(Uint8Array.from(binary,c=>c.charCodeAt(0)),f.name,'application/octet-stream');}break;}
      case 'sync':await syncCloud(true);break;case 'notifications':notifications();break;case 'install':if(installEvent){await installEvent.prompt();installEvent=null;}else toast(/iPad|iPhone/.test(navigator.userAgent)?'Safari’de Paylaş menüsünden “Ana Ekrana Ekle”yi seçin.':'Tarayıcı menüsünden “Uygulamayı yükle” veya “Ana Ekrana Ekle”yi seçin.');break;
      case 'voice':voice();break;case 'dismiss-alarm':dismissAlarm();break;case 'alarm-complete':complete(alarmId);dismissAlarm();break;case 'alarm-snooze':snoozeApply(alarmId,b.dataset.minutes);dismissAlarm();break;
      case 'close-toast':$('toast').hidden=true;undoAction=null;break;case 'load-more':limit+=100;render();break;
      case 'shortcuts':ask('Klavye kısayolları','<p>N: Yeni not<br>/: Arama<br>Esc: Pencereyi kapat<br>Ctrl + Enter: Kaydet</p>',[['ok','Tamam','primary']]);break;
      case 'category-add':{const name=$('category-name').value.trim(),color=$('category-color').value,icon=$('category-icon').value;if(!name||state.categories.some(c=>C.fold(c.name)===C.fold(name))){toast('Yeni ve farklı bir kategori adı yazın.');break;}commit('Kategori oluşturuldu.',s=>{s.categories.push({name,color,icon});s.categoriesUpdatedAt=new Date().toISOString();});break;}
      case 'category-edit':categoryEdit(b.dataset.name);break;case 'category-delete':{const name=b.dataset.name;if(name==='Diğer'){toast('Diğer kategorisi korunur.');break;}if(await ask('Kategoriyi sil',`<p>${esc(name)} silinsin mi? Kayıtlar Diğer kategorisine taşınır.</p>`)==='ok')commit('Kategori silindi.',s=>{s.categories=s.categories.filter(c=>c.name!==name);s.categoriesUpdatedAt=new Date().toISOString();s.notes.filter(n=>n.category===name).forEach(n=>{n.category='Diğer';stamp(n);});});break;}
    }
  });
  $('undo-button').addEventListener('click',()=>{if(undoAction){const action=undoAction;undoAction=null;action();}});
  $('note-form').addEventListener('submit',e=>{e.preventDefault();saveEditor();});
  $('note-form').addEventListener('input',()=>{clearTimeout(draftTimer);draftTimer=setTimeout(saveDraft,450);});
  $('editor').addEventListener('cancel',()=>saveDraft());$('editor').addEventListener('close',()=>{clearTimeout(draftTimer);if(recognition)recognition.stop();setTimeout(showNextAlarm,50);});$('details').addEventListener('close',()=>{detailId=null;setTimeout(showNextAlarm,50);});$('confirmation').addEventListener('close',()=>setTimeout(showNextAlarm,100));$('alarm-dialog').addEventListener('cancel',e=>{e.preventDefault();dismissAlarm();});
  let searchTimer;$('search').addEventListener('input',()=>{clearTimeout(searchTimer);searchTimer=setTimeout(()=>{query=$('search').value;limit=100;render();},120);});$('sort').addEventListener('change',render);
  document.addEventListener('change',event=>{const target=event.target;if(target.dataset.filter){filters[target.dataset.filter]=target.value;limit=100;render();}else if(target.dataset.select){target.checked?selected.add(target.dataset.select):selected.delete(target.dataset.select);renderBulk(visibleNotes());}else if(target.dataset.inline){updateInline(target.dataset.id,target.dataset.inline,target.value);}else if(target.dataset.editorSub!==undefined){editorSubs[+target.dataset.editorSub].completed=target.checked;saveDraft();}else if(target.dataset.detailSub!==undefined){updateSubtask(detailId,+target.dataset.detailSub,target.checked);}else if(target.dataset.cardSub!==undefined){updateSubtask(target.dataset.id,+target.dataset.cardSub,target.checked);}
    else if(['note-status','note-repeat'].includes(target.id)){refreshEditorExtras();saveDraft();}else if(target.id==='theme-select')commit('',()=>state.settings.theme=target.value,false);else if(target.id==='auto-archive')commit('Arşiv tercihi kaydedildi.',()=>{state.settings.autoArchive=target.checked;C.housekeeping(state);});else if(target.id==='import-file')importBackup(target.files[0]);else if(target.id==='note-files')addFiles(target.files);else if(target.id==='reminder-preset'){const now=new Date(),value=target.value;if(!value)return;if(value==='today17')now.setHours(17,0,0,0);else if(value==='tomorrow9'){now.setDate(now.getDate()+1);now.setHours(9,0,0,0);}else if(value==='3days'||value==='week')now.setDate(now.getDate()+(value==='week'?7:3));else now.setMinutes(now.getMinutes()+Number(value));if(now<Date.now()){toast('Bu saat geçmiş. Gelecek bir saat seçin.');target.value='';return;}$('note-alarm').value=localTime(now);saveDraft();}});
  document.addEventListener('keydown',e=>{const handle=e.target.closest('[data-subtask-drag]');if(handle&&['ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();moveSubtask(handle.dataset.id,+handle.dataset.index,e.key==='ArrowUp'?-1:1);return;}if(e.key==='Escape'&&subtaskDrag){e.preventDefault();endSubtaskDrag(false);return;}const editing=e.target.matches('input,textarea,select,[contenteditable=true]');if(e.key==='Enter'&&e.target.id==='subtask-input'){e.preventDefault();document.querySelector('[data-action="add-subtask"]').click();return;}if(e.key==='Enter'&&e.target.id==='detail-new-sub'){e.preventDefault();document.querySelector('[data-action="detail-add-sub"]').click();return;}if((e.ctrlKey||e.metaKey)&&e.key==='Enter'&&$('editor').open){e.preventDefault();saveEditor();return;}if(e.key==='Enter'&&e.target.id==='note-title'){e.preventDefault();saveEditor();return;}if(editing||e.ctrlKey||e.metaKey||e.altKey)return;if(e.key.toLocaleLowerCase('tr')==='n'&&!document.querySelector('dialog[open]')){e.preventDefault();openEditor();}else if(e.key==='/'&&!document.querySelector('dialog[open]')){e.preventDefault();$('search').focus();}});
  document.addEventListener('pointerdown',e=>{const handle=e.target.closest('[data-subtask-drag]');if(!handle||e.button!==0)return;const n=find(handle.dataset.id);if(!n||n.deletedAt)return;e.preventDefault();clearSubtaskDrag();handle.focus({preventScroll:true});handle.setPointerCapture(e.pointerId);const row=handle.closest('li'),rect=row.getBoundingClientRect();
    subtaskDrag={handle,row,list:row.parentElement,id:n.id,pointerId:e.pointerId,startX:e.clientX,startY:e.clientY,y:e.clientY,offset:e.clientY-rect.top,rect,active:false,frame:null};});
  document.addEventListener('pointermove',e=>{const drag=subtaskDrag;if(!drag||e.pointerId!==drag.pointerId)return;drag.y=e.clientY;if(!drag.active&&Math.hypot(e.clientX-drag.startX,e.clientY-drag.startY)>5){drag.active=true;drag.ghost=drag.row.cloneNode(true);drag.ghost.className='subtask-drag-ghost';drag.ghost.setAttribute('aria-hidden','true');drag.ghost.querySelectorAll('input,button').forEach(el=>el.disabled=true);Object.assign(drag.ghost.style,{left:drag.rect.left+'px',width:drag.rect.width+'px',top:drag.rect.top+'px'});document.body.append(drag.ghost);drag.row.classList.add('subtask-dragging');document.body.classList.add('subtask-reordering');positionSubtaskDrag();}});
  document.addEventListener('pointerup',e=>{if(subtaskDrag?.pointerId===e.pointerId)endSubtaskDrag(true);});
  document.addEventListener('pointercancel',e=>{if(subtaskDrag?.pointerId===e.pointerId)endSubtaskDrag(false);});
  document.addEventListener('lostpointercapture',e=>{if(subtaskDrag?.pointerId===e.pointerId)endSubtaskDrag(false);});
  document.addEventListener('dragstart',e=>{if(e.target.closest('[data-subtask-drag]')){e.preventDefault();return;}const card=e.target.closest('[data-card-id]');if(card){dragId=card.dataset.cardId;e.dataTransfer.setData('text/plain',dragId);e.dataTransfer.effectAllowed='move';}});
  document.addEventListener('dragover',e=>{const col=e.target.closest('[data-drop-status]');if(col){e.preventDefault();col.classList.add('drag-over');}});document.addEventListener('dragleave',e=>e.target.closest('[data-drop-status]')?.classList.remove('drag-over'));
  document.addEventListener('drop',e=>{const col=e.target.closest('[data-drop-status]');if(col){e.preventDefault();const id=e.dataTransfer.getData('text/plain')||dragId;if(find(id))updateInline(id,'status',col.dataset.dropStatus);dragId=null;}});
  // Touch users move cards with the same status selector; pointer long-press also supports dragging.
  let touchDrag=null;document.addEventListener('pointerdown',e=>{if(e.pointerType!=='touch'||e.target.closest('button,input,select,a'))return;const card=e.target.closest('.kanban [data-card-id]');if(!card)return;touchDrag={id:card.dataset.cardId,x:e.clientX,y:e.clientY,ready:false,timer:setTimeout(()=>{if(touchDrag)touchDrag.ready=true;},400)};});
  document.addEventListener('pointermove',e=>{if(touchDrag&&!touchDrag.ready&&Math.hypot(e.clientX-touchDrag.x,e.clientY-touchDrag.y)>12){clearTimeout(touchDrag.timer);touchDrag=null;}});document.addEventListener('pointerup',e=>{if(!touchDrag)return;clearTimeout(touchDrag.timer);const col=document.elementFromPoint(e.clientX,e.clientY)?.closest('[data-drop-status]');if(touchDrag.ready&&col)updateInline(touchDrag.id,'status',col.dataset.dropStatus);touchDrag=null;});document.addEventListener('pointercancel',()=>{if(touchDrag)clearTimeout(touchDrag.timer);touchDrag=null;});
  window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installEvent=e;});window.addEventListener('online',()=>syncCloud(dirty));window.addEventListener('offline',()=>syncStatus('Çevrimdışı · cihazda kayıtlı'));window.addEventListener('pagehide',saveDraft);document.addEventListener('visibilitychange',()=>{if(!document.hidden){tick();syncCloud(dirty);}});
  window.addEventListener('storage',e=>{if(e.key===C.KEY&&!$('editor').open){try{state=C.merge(state,JSON.parse(e.newValue));render();}catch{}}});
  matchMedia('(prefers-color-scheme: dark)').addEventListener('change',()=>{if(state.settings.theme==='system')setTheme();});
  // The v4 theme is copied during initialization before writing a v5 snapshot.
  if(C.housekeeping(state)){if(store()){dirty=true;queueSync();}}render();
  if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js').catch(e=>console.error('Çevrimdışı kurulum başarısız',e.message));
  navigator.serviceWorker?.addEventListener('message',e=>{if(e.data?.type==='open-note'){openDetail(e.data.id);}});
  syncCloud(false);setInterval(tick,4000);setInterval(()=>syncCloud(dirty),60000);setTimeout(tick,1000);
})();
