const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),C=require('../core.js');
const note=(data={})=>C.normalize({id:'a',title:'MERSİN İŞ TAKİBİ',createdAt:'2026-10-01T09:00:00Z',updatedAt:'2026-10-01T09:00:00Z',...data});
test('stored v4 or v5 records retain ids, text, alarms, categories and subtasks',()=>{
 const source=JSON.parse(fs.readFileSync(__dirname+'/../notes.json','utf8')),old=Array.isArray(source)?source:source.notes,state=C.migrate(source);assert.equal(state.notes.length,old.length);
 old.forEach((n,i)=>{const converted=state.notes[i];assert.equal(converted.id,String(n.id));for(const key of ['title','content','category','createdAt','updatedAt'])assert.equal(converted[key],n[key]);assert.equal(converted.alarmAt,n.alarmAt);assert.deepEqual(converted.subTasks.map(s=>[s.text,s.completed]),n.subTasks.map(s=>[s.text,s.completed]));});
});
test('legacy text/done/items aliases and unknown fields are preserved',()=>{const n=C.normalize({text:'Not',done:true,items:[{text:'Alt',done:true}],custom:'keep'});assert.equal(n.title,'Not');assert.equal(n.completed,true);assert.equal(n.custom,'keep');assert.equal(n.subTasks[0].completed,true);});
test('migration snapshots raw v4 bytes and never modifies them',()=>{const raw='[{"id":"a","title":"İş"}]',data=new Map([[C.LEGACY,raw]]),storage={getItem:k=>data.get(k)||null,setItem:(k,v)=>data.set(k,v)};const result=C.load(storage);assert.equal(result.state.notes.length,1);assert.equal(data.get('cepte_not_v4_backup'),raw);assert.equal(data.get(C.LEGACY),raw);});
test('corrupt v5 recovers lastgood and invalid items do not blank app',()=>{const data=new Map([[C.KEY,'{broken'],[C.KEY+'_lastgood',JSON.stringify([note()])]]),loaded=C.load({getItem:k=>data.get(k)||null,setItem:(k,v)=>data.set(k,v)});assert.equal(loaded.state.notes.length,1);assert.equal(loaded.issues.length,1);assert.equal(C.migrate([null,4,note()]).notes.length,1);assert.throws(()=>C.migrate({garbage:1}));});
test('Turkish case and diacritics search across all requested fields',()=>{const n=note({content:'Açıklama',tags:['Acil'],waitingFor:'Tarsus Birimi',subTasks:[{text:'Ölçüm'}]});for(const q of ['mersin','Mersin','İŞ','is','aciklama','#acil','TARSUS','ölçüm'])assert.equal(C.matches(n,{},q),true,q);});
test('date buckets use local calendar dates and waiting check date',()=>{assert.equal(C.bucket(note({dueDate:'2026-10-01'}),'2026-10-03'),'overdue');assert.equal(C.delta('2026-10-01','2026-10-03'),-2);assert.equal(C.bucket(note({dueDate:'2026-10-04'}),'2026-10-03'),'tomorrow');assert.equal(C.bucket(note({status:'Bekliyor',dueDate:'2026-10-08',checkDate:'2026-10-03'}),'2026-10-03'),'today');assert.equal(C.bucket(note(),'2026-10-03'),'undated');});
test('multiple filters AND together; smart priority and pinned order',()=>{const n=note({status:'Bekliyor',category:'İş',priority:'Yüksek',tags:['Rapor']});assert(C.matches(n,{status:'Bekliyor',category:'İş',priority:'Yüksek',tag:'Rapor'}));assert(!C.matches(n,{priority:'Düşük'}));const normal=note({id:'normal',dueDate:'2026-10-03'}),urgent=note({id:'urgent',priority:'Acil',dueDate:'2026-10-02'}),pinned=note({id:'pin',pinned:true});assert.deepEqual(C.sortNotes([normal,urgent,pinned],'smart','2026-10-03').map(n=>n.id),['pin','urgent','normal']);});
test('recurring completion creates just one next occurrence, preserving alarm hour',()=>{const s=C.migrate([note({dueDate:'2026-10-03',alarmAt:'2026-10-03T09:00:00Z',repeat:'daily',subTasks:[{text:'Alt',completed:false}]})]);C.complete(s,'a',new Date('2026-10-03T15:00:00Z'));assert.equal(s.notes.length,2);assert.equal(s.notes[1].dueDate,'2026-10-04');assert.equal(s.notes[1].completed,false);assert.equal(s.notes[1].subTasks[0].completed,false);assert.equal(s.notes[1].alarmAt,'2026-10-04T09:00:00.000Z');C.complete(s,'a');C.complete(s,'a');assert.equal(s.notes.length,2);});
test('weekday/week/month/year/custom schedules respect boundaries',()=>{assert.equal(C.nextDate(note({repeat:'weekdays',dueDate:'2026-10-02'}),'2026-10-02'),'2026-10-05');assert.equal(C.nextDate(note({repeat:'weekly',repeatDays:[1],dueDate:'2026-10-03'}),'2026-10-03'),'2026-10-05');assert.equal(C.nextDate(note({repeat:'monthly',dueDate:'2026-01-31'}),'2026-01-31'),'2026-02-28');assert.equal(C.nextDate(note({repeat:'yearly',dueDate:'2024-02-29'}),'2024-02-29'),'2025-02-28');assert.equal(C.nextDate(note({repeat:'custom',repeatEvery:3,dueDate:'2026-10-03'}),'2026-10-03'),'2026-10-06');});
test('merge respects newest edits, tombstones, trash and offline notes',()=>{const local=C.migrate([note({title:'Offline',updatedAt:'2026-10-03T10:00:00Z',deletedAt:'2026-10-03T10:00:00Z'})]),remote=[note({title:'Old'})];assert.equal(C.merge(local,remote).notes[0].title,'Offline');local.tombstones.push({id:'a',deletedAt:'2026-10-03T10:00:00Z'});assert.equal(C.merge(local,remote).notes.length,0);});
test('category removal survives reload; housekeeping honors 30/7-day limits',()=>{const s=C.migrate([note({completed:true,status:'Tamamlandı',completedAt:'2026-09-25T10:00:00Z'}),note({id:'trash',deletedAt:'2026-09-01T10:00:00Z'})]);s.categories=s.categories.filter(c=>c.name!=='Fikir');assert(!C.migrate(s).categories.some(c=>c.name==='Fikir'));s.settings.autoArchive=true;C.housekeeping(s,new Date('2026-10-03T10:00:00Z'));assert.equal(s.notes.length,1);assert(s.notes[0].archivedAt);assert.equal(s.tombstones[0].id,'trash');});
test('CSV has BOM, escaped quotes/newlines, Turkish labels and formula protection',()=>{const csv=C.csv([note({title:'=1+1',content:'İş; "not"\nyeni satır'})]);assert.equal(csv.charCodeAt(0),0xfeff);assert(csv.includes('Başlık'));assert(csv.includes("\"'=1+1\""));assert(csv.includes('""not""'));});
test('1000+ record filtering stays fast and complete',()=>{const notes=Array.from({length:2500},(_,i)=>note({id:String(i),title:'Kayıt '+i})),start=performance.now(),results=C.sortNotes(notes.filter(n=>C.matches(n,{},'kayıt')));assert.equal(results.length,2500);assert(performance.now()-start<2000);});
